### ISSUE TITLE
About the main file

### ISSUE THREAD

**Issue by x09326** [pfefferle/openwebicons#15]
Hi, I'm going to host this lib on [cdnjs](https://cdnjs.com).

But I don't know which files should be added.
Could you help me?
Thanks!
https://github.com/cdnjs/cdnjs/issues/9221

**Comment by pfefferle** [comment]
Cool, thanks!

You need all files from the `font` folder and the `openwebicons.css` and/or `openwebicons.min.css` from the css folder. Be sure to keep the folder structure, otherwise the CSS files will not correctly reference the fonts.

Let me know if you have some more questions or if I can help.

**Comment by pfefferle** [comment]
The main file should be `openwebicons.css` or `openwebicons.min.css`

**Comment by x09326** [comment]
Okay.
I will host it ASAP.
Thank you for your help!

**Comment by x09326** [comment]
@pfefferle 
How about other CSS files in `css` folder?
Do we need them?

**Comment by pfefferle** [comment]
No, just the two i mentioned... The other files are experiments or deprecated... I will remove work on removing them to lower the confusions...

**Comment by x09326** [comment]
@pfefferle 
It's okay.
Just in case so I check it.
Thanks!
