### ISSUE TITLE
Request: Movim Icon

### ISSUE THREAD

**Issue by mitchellurgero** [pfefferle/openwebicons#16]
Is this how we request icons?

EDIT: RE: https://movim.eu/

**Comment by pfefferle** [comment]
Do you have a link to a SVG version of the icon?

**Comment by mitchellurgero** [comment]
Unfortunately I only have the png version of the icon

**Comment by SeveFP** [comment]
Hi, the logo can be found here https://upload.wikimedia.org/wikipedia/commons/e/e8/Movim-logo.svg
Thanks @edhelas :smiley:

**Comment by pfefferle** [comment]
https://pfefferle.dev/openwebicons/icons/#openwebicons-movim
